### ISSUE TITLE
Upload source notebook

### ISSUE THREAD

**Issue by guangyaw** [ibleducation/jupyter-edx-grader-xblock#10]
In "INSTRUCTOR NOTEBOOK UPLOAD",
I meet a problem when uploading my notebook: 
"No Solution Cells Found in uploaded notebook! Are you sure this is the instructor version?".

Would you please provide a sample that would be a correct called "INSTRUCTOR NOTEBOOK"?

(My notebook is here :   
https://drive.google.com/file/d/1q7hA7_3Fh-d8P45V-J4LKfDl3vaBhL-g/view?usp=sharing
)

**Comment by labarba** [comment]
Your instructor notebook needs to comply with the `nbgrader` format. You might need to consult the [`nbgrader` documentation](https://nbgrader.readthedocs.io/en/stable/). We can't provide support for that.
